---
title: "Research foci"
output: html_document
---

## pCO2 measurements on voluntary observing ships (VOS)

Since 2003 automated pCO2 measurements are running on the VOS Finnmaid that commutes between Helsinki/Finland in the north and Travemünde/Germany in the south, thereby crossing the Central Baltic Sea several times a week. The resulting data set is available through SOCAT, comprises by now more than 3 million pCO2 measurements and allows us to determine the net primary production with highest spatio-temporal resolution and unreached accuracy. I was involved as chief data scientist in the compilation of the book ?Biogeochemical Transformations in the Baltic Sea: Observations Through Carbon Dioxide Glasses?.

Next steps? Blend Finnmaid data with observations from biogeochemical ARGO floats, hydrographical GETM model data and eventually remote sensing Chlorophyll estimates to produce a vertically and spatially fully resolved picture.

***

## Ocean acidification and alkalinity trends

The oceans take up Gigatonnes of anthropogenic CO2 year by year, thereby getting more and more acidic. This is process is simple chemistry at its best and therefore very predictable. Everywhere? Nope! In the Baltic Sea, I detected an increasing alkalinity trend that buffered the acidification expected from the atmospheric CO2 forcing by roughly 50%. How does it continue? No idea, because we do not yet completely understand the drivers for the past alkalinity rise. As the process might also inverse, we better start a reliable acidification monitoring soon and continue to keep an eye on the alkalinity, here and elsewhere in the world.

***

## pH methodology

We can measure ocean acidification since spectrophotometric pH measurements were introduced for oceanic conditions in the early 1990s. However, when I started my PhD we did not even have pH buffers for salinities < 20 and were still tracking pH in the Baltic Sea with glass electrodes (too low accuracy) at a few stations (too low spatial resolution) visited few times a year (too low temporal resolution). So, we had to solve this. With the help of the pH godfather himself, Dr. Andrew Dickson (SCRIPPS), and Germany's national metrological institute, PTB, we produced a series of pH buffer solutions in the salinity range 5-20, characterized the pH-dye m-Cresol purple and made sure it neither elevated amounts of dissolved organic matter nor hydrogen sulfide interfere with the spectrophotometric method. A paper trilogy for a PhD degree? Deal!
Now, please everybody go out to sea (or sent your drones) and use that stuff!

***

## BloomSail expedition

With our pCO2 measurement on VOS Finnmaid (see above) we miss one important information: The vertical extension of the CO2 draw down that we use to quantify net primary production. For the spring bloom we can fix that by looking at the vertical depletion of nutrients after the bloom. But in mid-summer, when cyanobacteria kick-in, which are capable of fixing N2 and are known to cope with very variable amounts of Phosphate, there is now other way than going out there and measure pCO2 at depth. Unfortunately, the blooms occur some when between June and August, so I somehow had to spend three months at sea. Classical research vessel cost ~10k? a day. My boss and many others would have killed me if I had even dared to ask. So, I rather relied on a small funding from the National Geographic Society and my beloved sailing vessel Tina V to spend summer 2018 at sea (though my boss still wanted to kill me at first). The outcome is expected to be published soon.
